//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorAppointmentBooking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AllAppointment
    {
        public int AptId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> DoctorId { get; set; }

        [DisplayFormat(DataFormatString ="{0:d}",ApplyFormatInEditMode =true)]
        public Nullable<System.DateTime> SlotDate { get; set; }
        public string Slots { get; set; }
        public string DrAvailability { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
