//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorAppointmentBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctorSlot
    {
        public int slotId { get; set; }
        public Nullable<int> doctorId { get; set; }
        public string slotTimes { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
