//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorAppointmentBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.doctorSlots = new HashSet<doctorSlot>();
            this.AllAppointments = new HashSet<AllAppointment>();
        }
    
        public int DocId { get; set; }
        public string DocName { get; set; }
        public string DocQualification { get; set; }
        public int DocExperience { get; set; }
        public string DocKnownLanguage { get; set; }
        public string DocCity { get; set; }
        public string DocBranch { get; set; }
        public string DocSpecialization { get; set; }
        public string DocImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doctorSlot> doctorSlots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllAppointment> AllAppointments { get; set; }
    }
}
